spring:
#  application:
#    name: service-provider
  banner:
    location: \banner.txt

  datasource:
    url: jdbc:mysql://35.184.208.171:3306/heybadminton?useUnicode=true&characterEncoding=UTF-8&serverTimezone=US/Eastern
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: will99
    password: Suces%2024
  redis:
    host: 35.184.208.171
    port: 6379
    password: Suces%2024
    database: 0
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8

mybatis:
  # 实体类别名---包路径
  type-aliases-package: com.heybadminton.entity
  # 映射文件位置
  mapper-locations: classpath*:**/mapper/*Mapper.xml
  configuration:
    # 使用日志打印 SQL 语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

upload_images:
  path: C:\Users\MistS\OneDrive\Desktop\gitcode\CS7319_software_architecture\client_server\front\public\upload_images


server:
  port: 8080

#server:
#  port: 8082

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/ # 指向 Eureka 注册中心
